<?php

use Illuminate\Database\Seeder;
use App\Pais;

class PaisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pais::create(['codigo' => 'AU', 'pais' => 'Australia']);
		Pais::create(['codigo' => 'CN', 'pais' => 'China']);
		Pais::create(['codigo' => 'JP', 'pais' => 'Japan']);
		Pais::create(['codigo' => 'TH', 'pais' => 'Thailand']);
		Pais::create(['codigo' => 'IN', 'pais' => 'India']);
		Pais::create(['codigo' => 'MY', 'pais' => 'Malaysia']);
		Pais::create(['codigo' => 'KR', 'pais' => 'Kore']);
		Pais::create(['codigo' => 'HK', 'pais' => 'Hong Kong']);
		Pais::create(['codigo' => 'TW', 'pais' => 'Taiwan']);
		Pais::create(['codigo' => 'PH', 'pais' => 'Philippines']);
		Pais::create(['codigo' => 'VN', 'pais' => 'Vietnam']);
		Pais::create(['codigo' => 'FR', 'pais' => 'France']);
		Pais::create(['codigo' => 'EU', 'pais' => 'Europe']);
		Pais::create(['codigo' => 'DE', 'pais' => 'Germany']);
		Pais::create(['codigo' => 'SE', 'pais' => 'Sweden']);
		Pais::create(['codigo' => 'IT', 'pais' => 'Italy']);
		Pais::create(['codigo' => 'GR', 'pais' => 'Greece']);
		Pais::create(['codigo' => 'ES', 'pais' => 'Spain']);
		Pais::create(['codigo' => 'AT', 'pais' => 'Austria']);
		Pais::create(['codigo' => 'GB', 'pais' => 'United Kingdom']);
		Pais::create(['codigo' => 'NL', 'pais' => 'Netherlands']);
		Pais::create(['codigo' => 'BE', 'pais' => 'Belgium']);
		Pais::create(['codigo' => 'CH', 'pais' => 'Switzerland']);
		Pais::create(['codigo' => 'AE', 'pais' => 'United Arab Emirates']);
		Pais::create(['codigo' => 'IL', 'pais' => 'Israel']);
		Pais::create(['codigo' => 'UA', 'pais' => 'Ukraine']);
		Pais::create(['codigo' => 'RU', 'pais' => 'Russian Federation']);
		Pais::create(['codigo' => 'KZ', 'pais' => 'Kazakhstan']);
		Pais::create(['codigo' => 'PT', 'pais' => 'Portugal']);
		Pais::create(['codigo' => 'SA', 'pais' => 'Saudi Arabia']);
		Pais::create(['codigo' => 'DK', 'pais' => 'Denmark']);
		Pais::create(['codigo' => 'IR', 'pais' => 'Ira']);
		Pais::create(['codigo' => 'NO', 'pais' => 'Norway']);
		Pais::create(['codigo' => 'US', 'pais' => 'United States']);
		Pais::create(['codigo' => 'MX', 'pais' => 'Mexico']);
		Pais::create(['codigo' => 'CA', 'pais' => 'Canada']);
		Pais::create(['codigo' => 'A1', 'pais' => 'Anonymous Proxy']);
		Pais::create(['codigo' => 'SY', 'pais' => 'Syrian Arab Republic']);
		Pais::create(['codigo' => 'CY', 'pais' => 'Cyprus']);
		Pais::create(['codigo' => 'CZ', 'pais' => 'Czech Republic']);
		Pais::create(['codigo' => 'IQ', 'pais' => 'Iraq']);
		Pais::create(['codigo' => 'TR', 'pais' => 'Turkey']);
		Pais::create(['codigo' => 'RO', 'pais' => 'Romania']);
		Pais::create(['codigo' => 'LB', 'pais' => 'Lebanon']);
		Pais::create(['codigo' => 'HU', 'pais' => 'Hungary']);
		Pais::create(['codigo' => 'GE', 'pais' => 'Georgia']);
		Pais::create(['codigo' => 'BR', 'pais' => 'Brazil']);
		Pais::create(['codigo' => 'AZ', 'pais' => 'Azerbaijan']);
		Pais::create(['codigo' => 'A2', 'pais' => 'Satellite Provider']);
		Pais::create(['codigo' => 'PS', 'pais' => 'Palestinian Territory']);
		Pais::create(['codigo' => 'LT', 'pais' => 'Lithuania']);
		Pais::create(['codigo' => 'OM', 'pais' => 'Oman']);
		Pais::create(['codigo' => 'SK', 'pais' => 'Slovakia']);
		Pais::create(['codigo' => 'RS', 'pais' => 'Serbia']);
		Pais::create(['codigo' => 'FI', 'pais' => 'Finland']);
		Pais::create(['codigo' => 'IS', 'pais' => 'Iceland']);
		Pais::create(['codigo' => 'BG', 'pais' => 'Bulgaria']);
		Pais::create(['codigo' => 'SI', 'pais' => 'Slovenia']);
		Pais::create(['codigo' => 'MD', 'pais' => 'Moldov']);
		Pais::create(['codigo' => 'MK', 'pais' => 'Macedonia']);
		Pais::create(['codigo' => 'LI', 'pais' => 'Liechtenstein']);
		Pais::create(['codigo' => 'JE', 'pais' => 'Jersey']);
		Pais::create(['codigo' => 'PL', 'pais' => 'Poland']);
		Pais::create(['codigo' => 'HR', 'pais' => 'Croatia']);
		Pais::create(['codigo' => 'BA', 'pais' => 'Bosnia and Herzegovina']);
		Pais::create(['codigo' => 'EE', 'pais' => 'Estonia']);
		Pais::create(['codigo' => 'LV', 'pais' => 'Latvia']);
		Pais::create(['codigo' => 'JO', 'pais' => 'Jordan']);
		Pais::create(['codigo' => 'KG', 'pais' => 'Kyrgyzstan']);
		Pais::create(['codigo' => 'RE', 'pais' => 'Reunion']);
		Pais::create(['codigo' => 'IE', 'pais' => 'Ireland']);
		Pais::create(['codigo' => 'LY', 'pais' => 'Libya']);
		Pais::create(['codigo' => 'LU', 'pais' => 'Luxembourg']);
		Pais::create(['codigo' => 'AM', 'pais' => 'Armenia']);
		Pais::create(['codigo' => 'VG', 'pais' => 'Virgin Island']);
		Pais::create(['codigo' => 'YE', 'pais' => 'Yemen']);
		Pais::create(['codigo' => 'BY', 'pais' => 'Belarus']);
		Pais::create(['codigo' => 'GI', 'pais' => 'Gibraltar']);
		Pais::create(['codigo' => 'MQ', 'pais' => 'Martinique']);
		Pais::create(['codigo' => 'PA', 'pais' => 'Panama']);
		Pais::create(['codigo' => 'DO', 'pais' => 'Dominican Republic']);
		Pais::create(['codigo' => 'GU', 'pais' => 'Guam']);
		Pais::create(['codigo' => 'PR', 'pais' => 'Puerto Rico']);
		Pais::create(['codigo' => 'VI', 'pais' => 'Virgin Island']);
		Pais::create(['codigo' => 'MN', 'pais' => 'Mongolia']);
		Pais::create(['codigo' => 'NZ', 'pais' => 'New Zealand']);
		Pais::create(['codigo' => 'SG', 'pais' => 'Singapore']);
		Pais::create(['codigo' => 'ID', 'pais' => 'Indonesia']);
		Pais::create(['codigo' => 'NP', 'pais' => 'Nepal']);
		Pais::create(['codigo' => 'PG', 'pais' => 'Papua New Guinea']);
		Pais::create(['codigo' => 'PK', 'pais' => 'Pakistan']);
		Pais::create(['codigo' => 'AP', 'pais' => 'Asia/Pacific Region']);
		Pais::create(['codigo' => 'BS', 'pais' => 'Bahamas']);
		Pais::create(['codigo' => 'LC', 'pais' => 'Saint Lucia']);
		Pais::create(['codigo' => 'AR', 'pais' => 'Argentina']);
		Pais::create(['codigo' => 'BD', 'pais' => 'Bangladesh']);
		Pais::create(['codigo' => 'TK', 'pais' => 'Tokelau']);
		Pais::create(['codigo' => 'KH', 'pais' => 'Cambodia']);
		Pais::create(['codigo' => 'MO', 'pais' => 'Macau']);
		Pais::create(['codigo' => 'MV', 'pais' => 'Maldives']);
		Pais::create(['codigo' => 'AF', 'pais' => 'Afghanistan']);
		Pais::create(['codigo' => 'NC', 'pais' => 'New Caledonia']);
		Pais::create(['codigo' => 'FJ', 'pais' => 'Fiji']);
		Pais::create(['codigo' => 'WF', 'pais' => 'Wallis and Futuna']);
		Pais::create(['codigo' => 'QA', 'pais' => 'Qatar']);
		Pais::create(['codigo' => 'AL', 'pais' => 'Albania']);
		Pais::create(['codigo' => 'BZ', 'pais' => 'Belize']);
		Pais::create(['codigo' => 'UZ', 'pais' => 'Uzbekistan']);
		Pais::create(['codigo' => 'KW', 'pais' => 'Kuwait']);
		Pais::create(['codigo' => 'ME', 'pais' => 'Montenegro']);
		Pais::create(['codigo' => 'PE', 'pais' => 'Peru']);
		Pais::create(['codigo' => 'BM', 'pais' => 'Bermuda']);
		Pais::create(['codigo' => 'CW', 'pais' => 'Curacao']);
		Pais::create(['codigo' => 'CO', 'pais' => 'Colombia']);
		Pais::create(['codigo' => 'VE', 'pais' => 'Venezuela']);
		Pais::create(['codigo' => 'CL', 'pais' => 'Chile']);
		Pais::create(['codigo' => 'EC', 'pais' => 'Ecuador']);
		Pais::create(['codigo' => 'ZA', 'pais' => 'South Africa']);
		Pais::create(['codigo' => 'IM', 'pais' => 'Isle of Man']);
		Pais::create(['codigo' => 'BO', 'pais' => 'Bolivia']);
		Pais::create(['codigo' => 'GG', 'pais' => 'Guernsey']);
		Pais::create(['codigo' => 'MT', 'pais' => 'Malta']);
		Pais::create(['codigo' => 'TJ', 'pais' => 'Tajikistan']);
		Pais::create(['codigo' => 'SC', 'pais' => 'Seychelles']);
		Pais::create(['codigo' => 'BH', 'pais' => 'Bahrain']);
		Pais::create(['codigo' => 'EG', 'pais' => 'Egypt']);
		Pais::create(['codigo' => 'ZW', 'pais' => 'Zimbabwe']);
		Pais::create(['codigo' => 'LR', 'pais' => 'Liberia']);
		Pais::create(['codigo' => 'KE', 'pais' => 'Kenya']);
		Pais::create(['codigo' => 'GH', 'pais' => 'Ghana']);
		Pais::create(['codigo' => 'NG', 'pais' => 'Nigeria']);
		Pais::create(['codigo' => 'TZ', 'pais' => 'Tanzani']);
		Pais::create(['codigo' => 'ZM', 'pais' => 'Zambia']);
		Pais::create(['codigo' => 'MG', 'pais' => 'Madagascar']);
		Pais::create(['codigo' => 'AO', 'pais' => 'Angola']);
		Pais::create(['codigo' => 'NA', 'pais' => 'Namibia']);
		Pais::create(['codigo' => 'CI', 'pais' => 'Cote DIvoire']);
		Pais::create(['codigo' => 'SD', 'pais' => 'Sudan']);
		Pais::create(['codigo' => 'CM', 'pais' => 'Cameroon']);
		Pais::create(['codigo' => 'MW', 'pais' => 'Malawi']);
		Pais::create(['codigo' => 'GA', 'pais' => 'Gabon']);
		Pais::create(['codigo' => 'ML', 'pais' => 'Mali']);
		Pais::create(['codigo' => 'BJ', 'pais' => 'Benin']);
		Pais::create(['codigo' => 'TD', 'pais' => 'Chad']);
		Pais::create(['codigo' => 'BW', 'pais' => 'Botswana']);
		Pais::create(['codigo' => 'CV', 'pais' => 'Cape Verde']);
		Pais::create(['codigo' => 'RW', 'pais' => 'Rwanda']);
		Pais::create(['codigo' => 'CG', 'pais' => 'Congo']);
		Pais::create(['codigo' => 'UG', 'pais' => 'Uganda']);
		Pais::create(['codigo' => 'MZ', 'pais' => 'Mozambique']);
		Pais::create(['codigo' => 'GM', 'pais' => 'Gambia']);
		Pais::create(['codigo' => 'LS', 'pais' => 'Lesotho']);
		Pais::create(['codigo' => 'MU', 'pais' => 'Mauritius']);
		Pais::create(['codigo' => 'MA', 'pais' => 'Morocco']);
		Pais::create(['codigo' => 'DZ', 'pais' => 'Algeria']);
		Pais::create(['codigo' => 'GN', 'pais' => 'Guinea']);
		Pais::create(['codigo' => 'CD', 'pais' => 'Cong']);
		Pais::create(['codigo' => 'SZ', 'pais' => 'Swaziland']);
		Pais::create(['codigo' => 'BF', 'pais' => 'Burkina Faso']);
		Pais::create(['codigo' => 'SL', 'pais' => 'Sierra Leone']);
		Pais::create(['codigo' => 'SO', 'pais' => 'Somalia']);
		Pais::create(['codigo' => 'NE', 'pais' => 'Niger']);
		Pais::create(['codigo' => 'CF', 'pais' => 'Central African Republic']);
		Pais::create(['codigo' => 'TG', 'pais' => 'Togo']);
		Pais::create(['codigo' => 'BI', 'pais' => 'Burundi']);
		Pais::create(['codigo' => 'GQ', 'pais' => 'Equatorial Guinea']);
		Pais::create(['codigo' => 'SS', 'pais' => 'South Sudan']);
		Pais::create(['codigo' => 'SN', 'pais' => 'Senegal']);
		Pais::create(['codigo' => 'MR', 'pais' => 'Mauritania']);
		Pais::create(['codigo' => 'DJ', 'pais' => 'Djibouti']);
		Pais::create(['codigo' => 'KM', 'pais' => 'Comoros']);
		Pais::create(['codigo' => 'IO', 'pais' => 'British Indian Ocean Territory']);
		Pais::create(['codigo' => 'TN', 'pais' => 'Tunisia']);
		Pais::create(['codigo' => 'GL', 'pais' => 'Greenland']);
		Pais::create(['codigo' => 'VA', 'pais' => 'Holy See (Vatican City State)']);
		Pais::create(['codigo' => 'CR', 'pais' => 'Costa Rica']);
		Pais::create(['codigo' => 'KY', 'pais' => 'Cayman Islands']);
		Pais::create(['codigo' => 'JM', 'pais' => 'Jamaica']);
		Pais::create(['codigo' => 'GT', 'pais' => 'Guatemala']);
		Pais::create(['codigo' => 'MH', 'pais' => 'Marshall Islands']);
		Pais::create(['codigo' => 'AQ', 'pais' => 'Antarctica']);
		Pais::create(['codigo' => 'BB', 'pais' => 'Barbados']);
		Pais::create(['codigo' => 'AW', 'pais' => 'Aruba']);
		Pais::create(['codigo' => 'MC', 'pais' => 'Monaco']);
		Pais::create(['codigo' => 'AI', 'pais' => 'Anguilla']);
		Pais::create(['codigo' => 'KN', 'pais' => 'Saint Kitts and Nevis']);
		Pais::create(['codigo' => 'GD', 'pais' => 'Grenada']);
		Pais::create(['codigo' => 'PY', 'pais' => 'Paraguay']);
		Pais::create(['codigo' => 'MS', 'pais' => 'Montserrat']);
		Pais::create(['codigo' => 'TC', 'pais' => 'Turks and Caicos Islands']);
		Pais::create(['codigo' => 'AG', 'pais' => 'Antigua and Barbuda']);
		Pais::create(['codigo' => 'TV', 'pais' => 'Tuvalu']);
		Pais::create(['codigo' => 'PF', 'pais' => 'French Polynesia']);
		Pais::create(['codigo' => 'SB', 'pais' => 'Solomon Islands']);
		Pais::create(['codigo' => 'VU', 'pais' => 'Vanuatu']);
		Pais::create(['codigo' => 'ER', 'pais' => 'Eritrea']);
		Pais::create(['codigo' => 'TT', 'pais' => 'Trinidad and Tobago']);
		Pais::create(['codigo' => 'AD', 'pais' => 'Andorra']);
		Pais::create(['codigo' => 'HT', 'pais' => 'Haiti']);
		Pais::create(['codigo' => 'SH', 'pais' => 'Saint Helena']);
		Pais::create(['codigo' => 'FM', 'pais' => 'Micronesi']);
		Pais::create(['codigo' => 'SV', 'pais' => 'El Salvador']);
		Pais::create(['codigo' => 'HN', 'pais' => 'Honduras']);
		Pais::create(['codigo' => 'UY', 'pais' => 'Uruguay']);
		Pais::create(['codigo' => 'LK', 'pais' => 'Sri Lanka']);
		Pais::create(['codigo' => 'EH', 'pais' => 'Western Sahara']);
		Pais::create(['codigo' => 'CX', 'pais' => 'Christmas Island']);
		Pais::create(['codigo' => 'WS', 'pais' => 'Samoa']);
		Pais::create(['codigo' => 'SR', 'pais' => 'Suriname']);
		Pais::create(['codigo' => 'CK', 'pais' => 'Cook Islands']);
		Pais::create(['codigo' => 'KI', 'pais' => 'Kiribati']);
		Pais::create(['codigo' => 'NU', 'pais' => 'Niue']);
		Pais::create(['codigo' => 'TO', 'pais' => 'Tonga']);
		Pais::create(['codigo' => 'TF', 'pais' => 'French Southern Territories']);
		Pais::create(['codigo' => 'YT', 'pais' => 'Mayotte']);
		Pais::create(['codigo' => 'NF', 'pais' => 'Norfolk Island']);
		Pais::create(['codigo' => 'BN', 'pais' => 'Brunei Darussalam']);
		Pais::create(['codigo' => 'TM', 'pais' => 'Turkmenistan']);
		Pais::create(['codigo' => 'PN', 'pais' => 'Pitcairn Islands']);
		Pais::create(['codigo' => 'SM', 'pais' => 'San Marino']);
		Pais::create(['codigo' => 'AX', 'pais' => 'Aland Islands']);
		Pais::create(['codigo' => 'FO', 'pais' => 'Faroe Islands']);
		Pais::create(['codigo' => 'SJ', 'pais' => 'Svalbard and Jan Mayen']);
		Pais::create(['codigo' => 'CC', 'pais' => 'Cocos (Keeling) Islands']);
		Pais::create(['codigo' => 'NR', 'pais' => 'Nauru']);
		Pais::create(['codigo' => 'GS', 'pais' => 'South Georgia and the South Sandwich Islands']);
		Pais::create(['codigo' => 'UM', 'pais' => 'United States Minor Outlying Islands']);
		Pais::create(['codigo' => 'GW', 'pais' => 'Guinea-Bissau']);
		Pais::create(['codigo' => 'PW', 'pais' => 'Palau']);
		Pais::create(['codigo' => 'AS', 'pais' => 'American Samoa']);
		Pais::create(['codigo' => 'BT', 'pais' => 'Bhutan']);
		Pais::create(['codigo' => 'GF', 'pais' => 'French Guiana']);
		Pais::create(['codigo' => 'GP', 'pais' => 'Guadeloupe']);
		Pais::create(['codigo' => 'MF', 'pais' => 'Saint Martin']);
		Pais::create(['codigo' => 'VC', 'pais' => 'Saint Vincent and the Grenadines']);
		Pais::create(['codigo' => 'PM', 'pais' => 'Saint Pierre and Miquelon']);
		Pais::create(['codigo' => 'BL', 'pais' => 'Saint Barthelemy']);
		Pais::create(['codigo' => 'DM', 'pais' => 'Dominica']);
		Pais::create(['codigo' => 'ST', 'pais' => 'Sao Tome and Principe']);
		Pais::create(['codigo' => 'KP', 'pais' => 'Kore']);
		Pais::create(['codigo' => 'FK', 'pais' => 'Falkland Islands (Malvinas)']);
		Pais::create(['codigo' => 'MP', 'pais' => 'Northern Mariana Islands']);
		Pais::create(['codigo' => 'TL', 'pais' => 'Timor-Leste']);
		Pais::create(['codigo' => 'BQ', 'pais' => 'Bonair']);
		Pais::create(['codigo' => 'MM', 'pais' => 'Myanmar']);
		Pais::create(['codigo' => 'NI', 'pais' => 'Nicaragua']);
		Pais::create(['codigo' => 'SX', 'pais' => 'Sint Maarten (Dutch part)']);
		Pais::create(['codigo' => 'GY', 'pais' => 'Guyana']);
		Pais::create(['codigo' => 'LA', 'pais' => 'Lao Peoples Democratic Republic']);
		Pais::create(['codigo' => 'CU', 'pais' => 'Cuba']);
		Pais::create(['codigo' => 'ET', 'pais' => 'Ethiopia']);
	}
}
